language: rust

rust:
  - stable

before_install:
  - nvm install node

script:
  - RUST_BACKTRACE=1 RUST_LOG="gh_issues=info" cargo run
  - cd frontend
  - npm install
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: frontend/build
  on:
    branch: master
